/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub fn crcHashSlow(
        bits: ::std::os::raw::c_int,
        poly: *const ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_void,
        hash: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn crcHashInit(
        bits: ::std::os::raw::c_int,
        poly: *const ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn crcHash64Init(
        bits: ::std::os::raw::c_int,
        poly: *const ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn crcHash(
        init: *mut ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_void,
        hash: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn crcHash64(
        init: *mut ::std::os::raw::c_void,
        data: *const ::std::os::raw::c_void,
        hash: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub static mut CRC_POLYS: [[[::std::os::raw::c_uchar; 16usize]; 16usize]; 129usize];
}
